name: Sportswear X-Change
whatsapp_url: "https://chat.whatsapp.com/CQXZLTcZiVl9oMvYWN5VTj"
email: "sportsxchangekerry@gmail.com"
facebook_url: "https://facebook.com/"
instagram_url: "https://instagram.com/"
partners:
  - name: NKEF
  - name: circular.ie
  - name: SuperValu
  - name: Comm. Centre
